<ul class="ft-safety">
    <li id="kx_verify" class="safety-1"><a href="https://ss.knet.cn/verifyseal.dll?sn=e15020411010857604sdpf000000&a=1&pa=0.6604958979008937" target="_blank"></a></li>
    <li class="safety-2">
        <a href="http://www.hd315.gov.cn/" target="_blank"></a>
    </li>
    <li class="safety-3">
        <a href="http://www.bj.cyberpolice.cn/index.do" target="_blank"></a>
    </li>
    <li class="safety-4">
        <a href="http://www.12377.cn/" target="_blank"></a>
    </li>
</ul>
<div class="footer-info" >
    <p><a class="beian_a" target="_blank" href="http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=11010802021578">北京市公安局海淀分局备案编号 11010802021578号</a><a href="javascript:void(0)" target="_blank">京ICP证备14020586号</a><a href="http://st.ufenqi.com/resources/app/img/footer/businessLicence.jpg" target="_blank">营业执照号：110108016963882</a><a href="javascript:void(0);" target="_blank">食品流通许可00证00号：SP1101081510244633</a> </p>
    <p><a>京海食药监械经营许20150358号</a><a>京海食药监械经营备20150440号</a></p>

    <p>Copyright 2016-2017,版权所有UFENQI.COM</p>
</div>